# Generated by Django 3.1.4 on 2020-12-12 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_videoinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='video_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
