# Generated by Django 3.1.4 on 2020-12-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_comments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='view',
            field=models.ImageField(blank=True, default=0, null=0, upload_to=''),
        ),
    ]
