# Generated by Django 3.1.4 on 2020-12-14 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20201214_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelinfo',
            name='subscribe',
            field=models.ManyToManyField(blank=True, related_name='subscribe_channel', to=settings.AUTH_USER_MODEL),
        ),
    ]
